"""insercao de dados

Revision ID: 1e809bf7b093
Revises: 5f94b41e28ff
Create Date: 2021-06-12 10:45:34.847692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e809bf7b093'
down_revision = '5f94b41e28ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
